name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          
        # Run only once a new release is created:
      - uses: actions/checkout@master
        if: ${{ steps.release.outputs.release_created }}
      - name: Create release files
        run: |
          zip -r release.zip version.txt assets-src .nvmrc package.json svgo.config.js webpack.config.js webpack.config.min.js
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./amplify.zip
          asset_name: amplify.zip
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
        if: ${{ steps.release.outputs.release_created }}
